name: Generate flattened IATI data

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */3 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          git config --global http.postBuffer 157286400
      - name: Generate data
        run: |
          python generate.py
      - name: Deploy EN
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: iati-data-access/data-en
          publish_dir: ./output/xlsx/en
          force_orphan: true
      - name: Deploy FR
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: iati-data-access/data-fr
          publish_dir: ./output/xlsx/fr
          force_orphan: true
      - name: Deploy ES
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: iati-data-access/data-es
          publish_dir: ./output/xlsx/es
          force_orphan: true
